# Generated by Django 3.2.20 on 2023-08-18 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20230818_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarEngine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine', models.CharField(max_length=20)),
                ('transmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cars.cartransmission')),
            ],
        ),
    ]
